---
swagger: "2.0"
info:
  description: "This is a simple API"
  version: "1.0.0"
  title: "Simple WhosePhoneNumber API"
  contact:
    email: "you@your-company.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
#host: "localhost:8000"
#basePath: "/"
tags:
- name: "Comments"
  description: "API about user comment"
- name: "Recently"
  description: "API for get recently list"
- name: "Information"
  description: "API provides the information about code and phone number"
schemes:
- "https"
- "http"
paths:
  /GetRecentReportByAreaCode:
    get:
      tags:
      - "Comments"
      summary: "searches Comment"
      description: "Retrieve all comment given area code\n"
      operationId: "recentReportByAreaCode"
      produces:
      - "application/json"
      parameters:
      - name: "AreaCode"
        in: "query"
        description: "Phone Number for Comments"
        required: true
        type: "string"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/CommentItem"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Comments"
  /GetRecentReportByPhoneNumber:
    get:
      tags:
      - "Comments"
      summary: "searches Comment"
      description: "Retrieve all comment given phone number\n"
      operationId: "recentReportByPhoneNumber"
      produces:
      - "application/json"
      parameters:
      - name: "PhoneNumber"
        in: "query"
        description: "Phone Number for Comments"
        required: true
        type: "string"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/CommentItem"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Comments"
  /GetCommentByPhoneNumber:
    get:
      tags:
      - "Comments"
      summary: "searches Comment"
      description: "Retrieve all comment given phone number\n"
      operationId: "getCommentByPhoneNumber"
      produces:
      - "application/json"
      parameters:
      - name: "PhoneNumber"
        in: "query"
        description: "Phone Number for Comments"
        required: true
        type: "string"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/CommentItem"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Comments"
  /GetVotesCountByPhoneNumber:
    get:
      tags:
      - "Comments"
      summary: "Vote Count"
      description: "Get vote safe and unsafe given phone number\n"
      operationId: "voteCount"
      produces:
      - "application/json"
      parameters:
      - name: "PhoneNumber"
        in: "query"
        description: "Phone Number for Vote Count"
        required: true
        type: "string"
      responses:
        200:
          description: "Get vote count for safe and unsafe given phonenumber"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/VoteCountItem"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Comments"
  /GetAllCallerType:
    get:
      tags:
      - "Comments"
      summary: "Get Caller Type List"
      description: "Retrieve List of Caller Type\n"
      operationId: "getAllCallerType"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "List of Caller Type"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/CallerTypeList"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Comments"
  /AddNewComment:
    post:
      tags:
      - "Comments"
      summary: "Add New Comment"
      description: "Add a new user comment\n"
      operationId: "addComment"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "CommentBody"
        description: "Phone Number for Comments"
        required: true
        schema:
          $ref: "#/definitions/CommentBody"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PostResult"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Comments"
  /PostVoteForPhoneNumber:
    post:
      tags:
      - "Comments"
      summary: "Add New Vote"
      description: "Post Safe Unsafe or Unknown\n"
      operationId: "postVote"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "VoteBody"
        description: "Phone Number for Comments"
        required: true
        schema:
          $ref: "#/definitions/VoteBody"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PostResult"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Comments"
  /GetReportedSafe:
    get:
      tags:
      - "Recently"
      summary: "Get Recently Reported as Safe"
      description: "Retrieve all comment given phone number\n"
      operationId: "getReportSafe"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Recently Report as Safe"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/RecentlySafeItem"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Recently"
  /GetReportedUnSafe:
    get:
      tags:
      - "Recently"
      summary: "Get Recently Reported as UnSafe"
      description: "Retrieve all comment given phone number\n"
      operationId: "getReportUnSafe"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Recently Report as UnSafe"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/RecentlySafeItem"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Recently"
  /GetRecentedCheckedPhoneNumber:
    get:
      tags:
      - "Recently"
      summary: "Get Recently Checked PhoneNumber"
      description: "Retrieve all comment given phone number\n"
      operationId: "getRecentlyCheckedPhoneNumber"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Recently Checked PhoneNumber"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/RecentlyCheckedPhoneNumberItem"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Recently"
  /GetRecentedComments:
    get:
      tags:
      - "Recently"
      summary: "Get Recently Checked PhoneNumber"
      description: "Retrieve all comment given phone number\n"
      operationId: "getRecentlyComments"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Recently Checked PhoneNumber"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/RecentlyCommentItem"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Recently"
  /GetStateByAreaCode:
    get:
      tags:
      - "Information"
      summary: "Get State for specific area code"
      description: "Retrieve state of Area Code\n"
      operationId: "getStateByAreaCode"
      produces:
      - "application/json"
      parameters:
      - name: "AreaCode"
        in: "query"
        description: "US Area Code"
        required: true
        type: "string"
      responses:
        200:
          description: "Recently Checked PhoneNumber"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/USAreaCodeInformation"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Information"
  /GetPhoneInformation:
    get:
      tags:
      - "Information"
      summary: "Get Information of Specific Information"
      description: "Retrieve the Information of Phonenumber\n"
      operationId: "getPhoneDescription"
      produces:
      - "application/json"
      parameters:
      - name: "phonenumber"
        in: "query"
        description: "Phone Number"
        required: true
        type: "string"
      - name: "log"
        in: "query"
        description: "Indicate logging or not."
        required: false
        type: "string"
      responses:
        200:
          description: "Recently Checked PhoneNumber"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PhoneInformation"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Information"
  /GetAllAreaCode:
    get:
      tags:
      - "Information"
      summary: "Get Description for specific area code"
      description: "Retrieve List of Area Code\n"
      operationId: "getAllAreaCode"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Recently Checked PhoneNumber"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/AreaCodeList"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Information"
definitions:
  CommentItem:
    type: "object"
    required:
    - "comment"
    - "date"
    - "id"
    - "ipaddress"
    - "username"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      username:
        type: "string"
        example: "Widget Adapter"
      comment:
        type: "string"
        example: "This is a debt collector"
      date:
        type: "string"
        format: "int32"
        example: "2016-08-29T09:12:33.001Z"
      ipaddress:
        type: "string"
        example: "192.168.1.1"
  VoteCountItem:
    type: "object"
    required:
    - "safe"
    - "unsafe"
    properties:
      safe:
        type: "string"
        example: "10"
      unsafe:
        type: "string"
        example: "15"
  RecentlySafeItem:
    type: "object"
    required:
    - "date"
    - "id"
    - "ipaddress"
    - "phonenumber"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      phonenumber:
        type: "string"
        example: "850-586-6200"
      ipaddress:
        type: "string"
        example: "192.168.1.1"
      date:
        type: "string"
        format: "int32"
        example: "2016-08-29T09:12:33.001Z"
  RecentlyCheckedPhoneNumberItem:
    type: "object"
    required:
    - "address"
    - "id"
    - "phonenumber"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      phonenumber:
        type: "string"
        example: "404-275-4585"
      address:
        type: "string"
        example: "Atlanta, Georgia, United States"
  RecentlyCommentItem:
    type: "object"
    required:
    - "comment"
    - "date"
    - "id"
    - "phonenumber"
    - "username"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      username:
        type: "string"
        example: "Widget Adapter"
      phonenumber:
        type: "string"
        example: "404-275-4585"
      comment:
        type: "string"
        example: "This is a debt collector"
      date:
        type: "string"
        format: "int32"
        example: "2016-08-29T09:12:33.001Z"
  USAreaCodeInformation:
    type: "object"
    required:
    - "city"
    - "country"
    - "current_time"
    - "id"
    - "state"
    - "timezone"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      country:
        type: "string"
        example: "United State"
      state:
        type: "string"
        example: "New Jersey"
      city:
        type: "string"
        example: "Jersey City"
      timezone:
        type: "string"
        example: "Eastern (UTC-05:00)"
      current_time:
        type: "string"
        format: "int32"
        example: "04:48 am"
  PhoneInformation:
    type: "object"
    required:
    - "areacode"
    - "carrier"
    - "city"
    - "country"
    - "county"
    - "id"
    - "interformat"
    - "prefix"
    - "state"
    - "usage_type"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      interformat:
        type: "string"
        example: "+1 718 349 9300"
      country:
        type: "string"
        example: "United State"
      state:
        type: "string"
        example: "New Jersey"
      city:
        type: "string"
        example: "Jersey City"
      areacode:
        type: "string"
        example: "718"
      prefix:
        type: "string"
        example: "349"
      county:
        type: "string"
        example: "Queens"
      carrier:
        type: "string"
        example: "VERIZON NEW YORK, INC."
      usage_type:
        type: "string"
        example: "Landline"
  CommentBody:
    type: "object"
    required:
    - "CallerTypeId"
    - "Comment"
    - "PhoneNumber"
    - "Username"
    properties:
      Username:
        type: "string"
        example: "John Smith"
      Comment:
        type: "string"
        example: "This is a comment."
      CallerTypeId:
        type: "string"
        example: "000001"
      PhoneNumber:
        type: "string"
        example: "201-200-0000"
  VoteBody:
    type: "object"
    required:
    - "IpAddress"
    - "PhoneNumber"
    - "VoteId"
    properties:
      VoteId:
        type: "string"
        example: "0"
      IpAddress:
        type: "string"
        example: "192.168.1.1"
      PhoneNumber:
        type: "string"
        example: "201-200-0000"
  PostResult:
    type: "object"
    required:
    - "description"
    - "id"
    - "result"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      result:
        type: "string"
        example: "OK"
      description:
        type: "string"
        example: "Description"
  AreaCodeList:
    type: "object"
    required:
    - "code"
    - "state"
    properties:
      code:
        type: "string"
        example: "201"
      state:
        type: "string"
        example: "New Jersey"
  CallerTypeList:
    type: "object"
    required:
    - "code"
    - "name"
    properties:
      code:
        type: "string"
        example: "0001"
      name:
        type: "string"
        example: "Unknown"
